name: ret_ad
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10.8
  - cudatoolkit
  - pytorch=1.13.1
  - torchvision=0.14.1
  - numpy=1.23.3
  - scikit-learn=1.1.3
  - transformers=4.24.0
  - pandas=1.4.4
  - fairseq
  - pip
  - pip:
    - dotmap
    - bitsandbytes-cuda117
    - torchmetrics==0.10.3